apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000
        env:
        - name: EXTERNAL_INTEGRATION_KEY
          valueFrom:
            secretKeyRef:
              name: backend-service-secrets
              key: EXTERNAL_INTEGRATION_KEY
