# Image configuration
image:
  repository: "{{ .Values.repository }}"  # Placeholder for repository; dynamically configured during deployment.
  tag: "{{ .Values.imageTag }}"           # Placeholder for image tag; dynamically configured during deployment.

# Default repository and tag values
repository: europe-west2-docker.pkg.dev/my-app-361806/cloud-test/data-service
imageTag: latest

service:
  type: LoadBalancer
  port: 5000

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
