image:
  repository: europe-west2-docker.pkg.dev/my-app-361806/cloud-test/data-service
  tag: latest

service:
  type: LoadBalancer
  port: 5000

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"
