# Image configuration
image:
  repository: europe-west2-docker.pkg.dev/my-app-361806/cloud-test/data-service
  imageTag: latest

service:
  type: LoadBalancer
  port: 5000

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1"

environment:
  mode: dev

rbac:
  enabled: true
  roles:
    - apiGroups: [""]
      resources: ["pods", "services", "configmaps"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get"]
serviceAccount:
  create: true
  name: ""
