image:
  repository: europe-west2-docker.pkg.dev/my-app-361806/cloud-test/backend-service
  tag: latest

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"
