# Image configuration
image:
  repository: europe-west2-docker.pkg.dev/my-app-361806/cloud-test/backend-service
  imageTag: latest

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"

environment:
  mode: dev


rbac:
  enabled: true
  roles:
    - apiGroups: [""]
      resources: ["pods", "services", "configmaps"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get"]
serviceAccount:
  create: true
  name: ""






