image:
  repository: europe-west2-docker.pkg.dev/my-app-361806/cloud-test/backend-service:latest
  tag: latest

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: backend-service.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - backend-service.example.com
      secretName: backend-service-tls
